stages:
  - test

.run_script: &run_script
  script:
    - pip install -r requirements.txt
    - git clone https://gitlab.labs.nic.cz/turris/foris-schema.git
    - cd foris-schema
    - (git checkout refs/remotes/origin/${CI_COMMIT_REF_NAME} || true)
    - python setup.py install
    - cd ..
    - git clone https://gitlab.labs.nic.cz/turris/foris-controller.git
    - cd foris-controller
    - (git checkout refs/remotes/origin/${CI_COMMIT_REF_NAME} || true)
    - python setup.py install
    - cd ..
    - git clone https://gitlab.labs.nic.cz/turris/foris-client.git
    - cd foris-client
    - (git checkout refs/remotes/origin/${CI_COMMIT_REF_NAME} || true)
    - python setup.py install
    - cd ..
    - python setup.py install
    - rm -rf {foris-controller,foris-schema,foris-client}
    - export LD_LIBRARY_PATH=:/usr/local/lib
    - python setup.py test

test_python2:
  image: registry.labs.nic.cz/turris/foris-ci/python2
  stage: test
  <<: *run_script

test_python3:
  image: registry.labs.nic.cz/turris/foris-ci/python3
  stage: test
  <<: *run_script
