before_script:
  - pip install virtualenv
  - virtualenv -p "$(which python)" /tmp/test

stages:
  - test

.run_script: &run_script
  script:
    - source /tmp/test/bin/activate

    - pip install .

    - pip install git+https://gitlab.nic.cz/turris/foris-controller/foris-controller.git#egg=foris-controller
    - pip install git+https://gitlab.nic.cz/turris/foris-controller/foris-controller-testtools.git#egg=foris-controller-testtools

    - python setup.py test

test_python3:
  image: registry.nic.cz/turris/foris-ci/python3
  stage: test
  <<: *run_script
